### ISSUE TITLE
Projection of the label embedding matrix

### ISSUE THREAD

**Issue by zyu-wok** [ppontisso/Extreme-Multi-Label-Classification#2]
Hi @ppontisso ,

First, this not a code-related issue, but regarding the paper. 
I am trying to implement the model in the [paper from Zhang et al](https://arxiv.org/pdf/1704.03718.pdf) and saw your code. It is indeed very helpful, thanks!
Since I haven't been able to get in contact with author yet, I want to try my luck here:
Although you simply used the proximity matrix to project the label embedding, I was wondering if you tried to embed the labels via deepwalk?
My question is specifically regarding to step 3 in Algorithm 1, the V_y in 

> f_Y = {f_Y | f_Y = 1 / (nnz(y)) * **V_y**, for y in Y}

Do you know how **V_y** is calculated?

- If nnz(y) = 1, V_y would simply be the corresponding row in V, no problem. 
- But if nnz(y) > 1, what should be the corresponding V_y?

If you can't help, or this is the wrong platform, let me know and I will close issue.

Cheers!

**Comment by ppontisso** [comment]
Hello,
I am glad it helped you but unfortunately, I have not tried the deepwalk embedding and I don't know the answer to your question,
I hope you have luck finding it !
Cheers

**Comment by zyu-wok** [comment]
Thank you for the response!
